### PR TITLE
Replaced Discord channel names with links to the channel

### PR DESCRIPTION
**Pull request by Siddhart**
The Helium Discord server has a lot of channels. For someone who is reading the docs it can be really hard to find the channel in the server. 

I replaced every discord channel name with a link to the discord channel so the user can simply click on it and it will redirect them to the correct channel.

### CODE REVIEW

**Comment by PharkMillups** [comment]
Wow. Thanks for this! Does clicking these actually work for people using the discord app? I can't seem to get it to function correctly.

**Comment by Siddhart** [comment]
Clicking on the links does not redirect the user to the app. I did some research and there is a way to do this. I will edit the links so they also open the app ;)

**Comment by Siddhart** [comment]
All the links should now redirect the user to the Discord application.

**Comment by PharkMillups** [comment]
Huh. Very cool. I'll fix this small conflict then merge. Thanks!

**Review by samgutentag — COMMENTED** [review]
links all good, formatting applied

**Comment by samgutentag** [comment]
Thank you so much @Siddhart for this contribution! As part of a broader set of updates, these changes were consolidated into #904 

Closing this PR for clarity, appreciate you taking the time

**Pull request closed without merging**
