### PR TITLE
Move content for compression NFTs

### PR DESCRIPTION
**Pull request by DanielChrobak**
Also moves the Compression NFTs section from the rewardable entities page to its own page that has been "in progress" for a while

### CODE REVIEW

**Comment by waveform06** [comment]
Can you also remove these 2 lines from compression-nfts
"import LegacyContentBanner from '@site/src/theme/LegacyContentBanner'
<LegacyContentBanner />"

**Review by jthiller — CHANGES_REQUESTED** [review]
Let's revert changes on the hotspot-makers page and make this a compression nfts PR.
Sounds like there are some other plans in the works for the maker page.

**Review by jthiller — APPROVED** [review]

**Comment by jthiller** [comment]
Thank you for submitting updates to the Helium Docs as part of the Solana Scribes Hackathon! Please follow the instructions in this form so we may begin issuing awards.

[https://forms.gle/z4ovMHYDo7pzy8TN6](https://forms.gle/z4ovMHYDo7pzy8TN6)

Please complete this form by March 15, 2024. (Approximately 1 week from today). We had SO MANY great submissions and we’re eager to distribute the awards to all of the contributors.

**Comment by DanielChrobak** [comment]
starfish

**Pull request merged**
