### PR TITLE
Update frequency-plans.mdx

### PR DESCRIPTION
**Pull request by yoshincha**
Hello. I made a small revision about the current norms regarding the radioelectric spectrum of the country Venezuela, finding documentation of the regulatory entity of this country, called "Conatel".

The Helium network uses the ISM Band, which is a band defined by The ITU Radio Regulations. The ITU on its website, attached, specifies that the ISM bands with the frequency range 902-928MHz is an ISM band for region 2 (No. 5,150).

Very well, going into a little detail on the website of the Venezuelan regulatory body, I find that "CONATEL" (regulatory body) is based on the ITU to define its regulation of radioelectric space, and, I find that on its website, The country Venezuela is defined in Region 2, indicating that the frequencies 902-928MHz are for the ISM band, indicating that it is based on the number 5.150 of the ITU.

Well, investigating a little more, in CONATEL (regulatory body of radioelectric space), I find in detail, what each band and each frequency is used for within the country, and I see that the 902-928MHz frequency is not used for any purpose at the moment, it is not designated under license and is free for use as an ISM band. Only the currently used bands appear.
See Chapter III, National Notes. Article 10.

On the thethingsnetwork website, it tells us that the band to use for loRaWAN is ISM, and in its table of common frequency plans it tells us that US902-928 or its common name US915 is used in Venezuela.

Please read this information carefully, in order to improve the helium network and if necessary, make updates based on reliable documents under investigation. I hope to contribute to the Helium network and take this valuable information into consideration to make this great project grow.

https://en.wikipedia.org/wiki/ISM_radio_band

https://www.itu.int/dms_pubrec/itu-r/rec/sm/R-REC-SM.1896-1-201809-I!!PDF-E.pdf

http://www.conatel.gob.ve/files/consulta/PA_CUNABAF_CP.pdf

https://www.thethingsnetwork.org/docs/lorawan/frequency-plans/

https://www.thethingsnetwork.org/docs/lorawan/regional-parameters/

https://cloudrf.com/docs/helium-lora-hotspot-modeling/
ISM
conatel

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thank you very much for the detailed investigation! 

@lthiery Can you take a quick look here?

**Comment by lthiery** [comment]
Hello, @yoshincha and thank you for this write up. 

The Helium Network refers  itself to the [LoRa Alliances regional specifications]( https://lora-alliance.org/wp-content/uploads/2021/05/RP002-1.0.3-FINAL-1.pdf). Per that document, the only valid frequency plan for Venezuela is marked as AS923_1 and, therefore, we abide by this.

I'm hardly an expert of why it is that way, but as the Helium Network provides LoRaWAN infrastructure, we should abide by the specifications set forth by the LoRa Alliance. It might be worth raising the issue with them if you believe it is erroneous.

**Comment by yoshincha** [comment]
> Hello, @yoshincha and thank you for this write up.
> 
> The Helium Network refers itself to the [LoRa Alliances regional specifications](https://lora-alliance.org/wp-content/uploads/2021/05/RP002-1.0.3-FINAL-1.pdf). Per that document, the only valid frequency plan for Venezuela is marked as AS923_1 and, therefore, we abide by this.
> 
> I'm hardly an expert of why it is that way, but as the Helium Network provides LoRaWAN infrastructure, we should abide by the specifications set forth by the LoRa Alliance. It might be worth raising the issue with them if you believe it is erroneous.

In the document, it is specified that region 2 corresponds to band 915. In my country's document and in other documents on which LoraWan is based, Venezuela is Region 2, and yet LoraWan says that Venezuela is As923. I do not know why, only, I refer to the evidence, to the facts. Of course, it would be worth debating and correcting, if necessary. I insist, Venezuela is Region 2, 915 Band, as indicated by the law of the radioelectric space of my country, and based on national laws, in order not to infringe any crime or invade a band that is in use, the Legal band to use is 915Mhz. As you can see, in the Helium Explorer Map, the connected devices are all 915Mhz. It would not be worth connecting a device with a different frequency to commit a crime and not connect with the other devices.

**Comment by yoshincha** [comment]
image

**Comment by lthiery** [comment]
@yoshincha does [your documentation not say that 902-928 MHz is acceptable](https://user-images.githubusercontent.com/85315409/129781791-a84ed91c-dd3d-4daa-9582-67a628765b78.PNG)? AS923_1 is within that range? Therefore, I am not sure what the concern is exactly?

> As you can see, in the Helium Explorer Map, the connected devices are all 915Mhz. 

Fortunately, US915 and AS923_1 generally shared identical front-ends. So the same physical device can operate on either subband with the right software configuration. So if someone has deployed a 915 MHz hotspot, it should work just fine when configured for AS923_1.

**Comment by samgutentag** [comment]
thanks for this! We’ll be making a broader update to this page and will capture the fixes there. Closing but appreciate you taking the time.

**Pull request closed without merging**
