### PR TITLE
Add Victor v4xx Self Provisioning Guide for VLINK

### PR DESCRIPTION
**Pull request by kent-williams**

### CODE REVIEW

**Comment by suprnrdy** [comment]
At the end, direct the user to the VLink manual to complete connection of the device to the VLink dashboard/app.

**Comment by suprnrdy** [comment]
Some FAQ's or "Good to knows":

What does ErrorCode in the Uplink mean?
ErrorCode: 0 = Lid Closed
ErrorCode: 1 = Lid is Open

What sequence of messages should I expect (in console)?
1. Series of 10-15 messages - These include network join, power up status, other status messages
2. Then 5 messages 10 minutes apart
3. Then a status message every 23 hours

What sequence of messages should I expect (in vlink dashboard)?
In the activity log you will see "Trap Powered Up" and a series of "Trap Status" logs. 

What are the button presses?
If unit is off:
- Pressing the button will turn it on and initialize the unit
If unit is on:
- 1 quick button press will send a status message
- 1 Long button press will turn the unit off

**Comment by kent-williams** [comment]
@PharkMillups This is ready to go. Feel free to push any last minute changes to get it live sooner!

**Review by PharkMillups — APPROVED** [review]
Looks great. Merging.

**Pull request merged**
