### PR TITLE
Update vehnt.mdx

### PR DESCRIPTION
**Pull request by heatedlime**
Removed reference of realms and put in links to helium vote.

### CODE REVIEW

**Comment by heatedlime** [comment]
Governance tab on HW

**Comment by heatedlime** [comment]
Example locked tokens

**Comment by heatedlime** [comment]
Your voting power

**Comment by heatedlime** [comment]
lockup type

**Comment by heatedlime** [comment]
duration

**Comment by heatedlime** [comment]
delegate to subdao

**Comment by heatedlime** [comment]
estimated changes

**Comment by waveform06** [comment]
is this the right PR for the images?

**Comment by heatedlime** [comment]
> is this the right PR for the images?

Yes. Adding the images now, haven’t published yet.

**Comment by heatedlime** [comment]
undelegate

**Comment by heatedlime** [comment]
start unlock

**Comment by heatedlime** [comment]
no sol error

**Comment by heatedlime** [comment]
> is this the right PR for the images?

You're right, this is the wrong PR for these images. Removing them

**Pull request closed without merging**
