### PR TITLE
Update faqs-resources-providers.mdx

### PR DESCRIPTION
**Pull request by Boyasapiens**
Adding multipool.app to the list of providers

### CODE REVIEW

**Comment by Boyasapiens** [comment]
Just want to add www.multipool.app to the resources providers page

**Review by varshard — APPROVED** [review]

**Comment by PharkMillups** [comment]
Awesome. Thanks. Merging.

**Comment by PharkMillups** [comment]
Actually, I spoke too soon. Sorry. We just redid the providers listing. Can you recut this against master?

**Comment by PharkMillups** [comment]
Closing for now. Please resubmit this PR against the updated page.

**Pull request closed without merging**
