### PR TITLE
Update deployment-guide.mdx

### PR DESCRIPTION
**Pull request by densone**
added some relevant info to source build instructions

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks, dens. @ericjohncarlson Can you take a quick look?

**Comment by ericjohncarlson** [comment]
@densone Sean, not sure why, but I can't see the details of that pull - it shows up as a 404.  Is your fork marked private?

**Comment by ericjohncarlson** [comment]
@densone I swear I commented on this PR (or a duplicate of it) earlier this week.  Am I losing my mind?  I don't see it in closed PRs...

**Comment by densone** [comment]
Now I see them all. Ok let me look at your comments and update.

**Review by samgutentag — APPROVED** [review]

**Pull request merged**
