### PR TITLE
Add: add seeed products including new sensecap and lorawan dev kit

### PR DESCRIPTION
**Pull request by MatthewJeffson**
Add six new sensecap products and one lorawan dev kit

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks! @illperipherals - Can you spend some time reviewing this please?

**Review by illperipherals — CHANGES_REQUESTED** [review]
Please include your additions in sidebarsDocs.js so that they may be navigated to.

**Comment by MatthewJeffson** [comment]
Hello, I have updated sidebarsDocs.js and add the additions. Would you mind help to review it? Thank you very much.

**Review by illperipherals — APPROVED** [review]

**Comment by illperipherals** [comment]
Seems to look good here.

**Pull request merged**
