### PR TITLE
Update frequency-plans.mdx

### PR DESCRIPTION
**Pull request by alifarhat1111**

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks. Do you have any links / supporting docs we can include as background?

**Comment by alifarhat1111** [comment]
> Thanks. Do you have any links / supporting docs we can include as background?


Dear PharkMillups,

Thanks for your review. 
You can enter this link and check thr fact that such frequencies are used with helium hotspot already in Lebanon:

https://explorer.helium.com/coverage#2.2/39.83/-65.58

For any questions do not hesitate.

Regards,

**Comment by alifarhat1111** [comment]
Dear PharkMillups,

Thanks for your review.
You can enter this link and check thr fact that such frequencies are used with helium hotspot already in Lebanon:

https://explorer.helium.com/coverage#2.2/39.83/-65.58

For any questions do not hesitate.

Regards,

On 4 Jun 2021, at 16:45, Mark Phillips ***@***.***> wrote:

﻿

Thanks. Do you have any links / supporting docs we can include as background?

**Comment by PharkMillups** [comment]
Thanks for this. However, I was looking for some docs specific to Lebanon that show that EU863-870 and EU433 are usable for Lorawan devices. Typically these would come from some sort of government agency (like the FCC in the US) or another local governing body.

**Comment by alifarhat1111** [comment]
Dear Mr. Philips,

Please find the needed information in the link below:

https://link.springer.com/content/pdf/bbm%3A978-1-4842-4357-2%2F1.pdf

Regards,


On 4 Jun 2021, at 17:21, Mark Phillips ***@***.***> wrote:

﻿

Thanks for this. However, I was looking for some docs specific to Lebanon that show that EU863-870 and EU433 are usable for Lorawan devices. Typically these would come from some sort of government agency (like the FCC in the US) or another local governing body.

**Comment by King-of-Spades** [comment]
## Research 
(caveat emptor, I'm new to this info)

1. Read the [cited PDF](https://link.springer.com/content/pdf/bbm%3A978-1-4842-4357-2%2F1.pdf) (Copyright 2019). It matches the update for Lebanon: **(EU863-870 EU433)**.  
2. It cites this dead page: https://lora-alliance.org/resource-hub/lorawantm-regional-parameters-v11rb
3.  Queried **lorawantm-regional-parameters-v11rb** and found article (Nov. 2020): [LoRa Alliance® Publishes Latest LoRaWAN® Regional Parameters...](https://lora-alliance.org/lora-alliance-press-release/lora-alliance-publishes-latest-lorawan-regional-parameters-includes-support-for-new-data-rates-that-expand-network-capacity-for-specific-use-cases/)
4. Article points to [RP2-1.0.2 LoRaWAN® Regional Parameters](https://lora-alliance.org/resource_hub/rp2-102-lorawan-regional-parameters/) which gives the same answer. Lebanon: **(EU863-870 EU433)**.  

## Conclusion
The requested edit is either _correct_ as of Nov. 2020, OR it's an easy mistake to make / probably need to find better ref. docs.

**Comment by King-of-Spades** [comment]
P.S. If my citation is accurate for this PR, then it appears the Nov. 2020 reference also confirms the findings in this PR (for Georgia): https://github.com/helium/docs/pull/387

**Comment by Topius** [comment]
Lebanon (LB)
433.05 – 434.79 MHz EU433
863 - 870 MHz EU863-870

As seen In Lora Alliance Document: https://lora-alliance.org/wp-content/uploads/2020/11/RP_2-1.0.2.pdf

**Comment by lthiery** [comment]
We should be approaching "correcting regions" by focusing on what is configured in the [Miner repo](https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv#L13). The regions defined there have their channel plans defined [here](https://github.com/helium/miner/blob/30efcb0806fc42a390802357486bfe77ce76fea6/config/sys.config#L108).

In this case, Lebanon is already defined as EU868 in the [`countries_reg_domains.csv`](https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv#L122). The core issue is that this documentation is out of sync with `countries_reg_domains.csv`. 

It would be nice to generate this page from `countries_reg_domains.csv`, but we will also be embedding `countries_reg_domains.csv` into blockchain chain vars soon. So we will eventually want to automate the generation of this documentation from the chain vars.

**Comment by Topius** [comment]
Its not that case for why we trying this.

 BObcat uses Frequency-Plans.mdx to filter countries it seems, as when entering on Webpage it guides you there and tells you sorry we dont support your country frequency.

that is the first thing needs to be updated so people can Order And check their old Order Invoices On Bobcat and any webpage that will plan to use that  as a Frequency-Plans.mdx tool  (as currently checking invoices only accessible with VPN).

And automation should happen from Updated Lora Alliance documents as 2020 one already says Georgia, Ukraine, Lebanon are in the list

**Comment by lthiery** [comment]
We should use Lorawan documents as the source of truth, but I still suggest manual editing of [`countries_reg_domains.csv`](https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv) (and soon to be chain vars) and then do docs generation from there, since CSV to Markdown should be relatively trivial.

**Comment by King-of-Spades** [comment]
@lthiery auto-generation from that CSV would omit the "regulatory document" field. Does that field need to be preserved, or is it superseded?

(For example by the LoRaWAN doc or other central reference(s))

**Comment by lthiery** [comment]
> @lthiery auto-generation from that CSV would omit the "regulatory document" field. Does that field need to be preserved, or is it superseded?
> 
> (For example by the LoRaWAN doc or other central reference(s))

That's a very good point. I've been thinking a lot about this this week and I think we should just allow that column to disappear. I don't think our current method of debating frequency plans via PRs is very scalable and we will likely find a new process. So for the sake of expediency and getting the frequency references to match, I would just go forth with CSV => Markdown and call it a day for now. We can always pull back in the `regulatory document` column later from the git history if we want to find a way to recover it.

**Comment by King-of-Spades** [comment]
Should be resolved by https://github.com/helium/docs/pull/418

**Pull request closed without merging**
