### PR TITLE
Update mine-hnt.mdx

### PR DESCRIPTION
**Pull request by ke6jjj**
At @Xullien and @nosmaster89's suggestions.

### CODE REVIEW

**Comment by abhay** [comment]
Reasonable change. I'd update the page slug, specify it's "Helium IOT Hotspot" or "Helium LoRaWAN Hotspots" and change the section header in the menu on the left too

**Comment by ke6jjj** [comment]
**Note**: This entire page is slated for removal, so it may not be worth arranging too many deck chairs.

**Comment by jthiller** [comment]
arranged more deck chairs.

**Comment by samgutentag** [comment]
image

**Review by samgutentag — APPROVED** [review]

**Pull request merged**
