### PR TITLE
Escrow UI Widget

### PR DESCRIPTION
**Pull request by Perronef5**
## CHANGES 💻

- Add OUI Escrow Widget (Given a OUI Key it will fetch the escrow account, escrow account balance and the delegated data credits account)

## DEMO 📷

https://github.com/helium/docs/assets/19807431/f808ddaf-a1cd-434e-a8fd-55f2db775c16

### CODE REVIEW

**Review by jthiller — APPROVED** [review]
Happy to have this in docs!!

**Comment by jthiller** [comment]
Thank you for submitting updates to the Helium Docs as part of the Solana Scribes Hackathon! Please follow the instructions in this form so we may begin issuing awards.

https://forms.gle/z4ovMHYDo7pzy8TN6  

Please complete this form by March 15, 2024. (Approximately 1 week from today). We had SO MANY great submissions and we’re eager to distribute the awards to all of the contributors.

**Comment by jthiller** [comment]
Apologies, something happened to the Google forms link. This one should work: [https://forms.gle/z4ovMHYDo7pzy8TN6](https://forms.gle/z4ovMHYDo7pzy8TN6)

**Comment by Perronef5** [comment]
DeWiCats

**Pull request merged**
