### PR TITLE
Update: Change the SenseCAP list

### PR DESCRIPTION
**Pull request by MatthewJeffson**

### CODE REVIEW

**Comment by MatthewJeffson** [comment]
Hi, we have changed the order of SenseCAP list. Please help us to change it.
Thank you very much!

**Comment by samgutentag** [comment]
@BilltheWorld, what is the motivation behind this page reorder?

**Comment by MatthewJeffson** [comment]
Hi, we want our latest SenseCAP products ranking at the front of the list, for viewers a better look about this new information: we have SenseCAP version 2.0 now!!! 
Something like that :)
Thank you very much.

**Review by samgutentag — APPROVED** [review]
all clear

**Pull request merged**
