### PR TITLE
Multi validator stake resolves #333

### LINKED ISSUE #333: Validator: document support staking multiple validators at once
Issue here: https://github.com/helium/helium-wallet-rs/issues/127

Pr here: https://github.com/helium/helium-wallet-rs/pull/132

### PR DESCRIPTION
**Pull request by jkowalcz**
Documents the multi validator staking commands resolves #333

### CODE REVIEW

**Comment by PharkMillups** [comment]
Very nice. 

@ericjohncarlson Can you give this a quick look / +1 at your leisure?

**Comment by ericjohncarlson** [comment]
@jkowalcz Nice addition! 

I do have one comment - this is a pretty specific use case for a very small set of validator operators.  I don't know if it adds value to the Deployment Guide page.

What we should do is copy or migrate the Validators Wallet page (https://docs.helium.com/mine-hnt/validators/testnet/wallet/) and add this section to that Validators Wallet page.  Then we could link to it from the Validators Deployment Guide with a text link "staking multiple validators?" to link out.

**Comment by jkowalcz** [comment]
> @jkowalcz Nice addition!
> 
> I do have one comment - this is a pretty specific use case for a very small set of validator operators. I don't know if it adds value to the Deployment Guide page.
> 
> What we should do is copy or migrate the Validators Wallet page (https://docs.helium.com/mine-hnt/validators/testnet/wallet/) and add this section to that Validators Wallet page. Then we could link to it from the Validators Deployment Guide with a text link "staking multiple validators?" to link out.

Yeah that would be a better way.  I didn't know we had that in a separate file in testnet section.

**Comment by jkowalcz** [comment]
@ericjohncarlson How about this?

**Comment by PharkMillups** [comment]
@ericjohncarlson We good to go here?

**Comment by ericjohncarlson** [comment]
> @ericjohncarlson We good to go here?

Yes!  @jkowalcz thanks for adding the links in navigation as well.  I think this is good.

**Comment by PharkMillups** [comment]
The A Team firing on all cylinders. Thanks, gents!

**Review by PharkMillups — APPROVED** [review]

**Pull request merged**
