### PR TITLE
add wdriot oceania to lns list - bones

### PR DESCRIPTION
**Pull request by ccall48**

### CODE REVIEW

**Comment by jthiller** [comment]
Hi, excited to get this added. Is there a page where new users can get more information on pricing and sign up?

**Comment by ccall48** [comment]
Not at the moment joey I need more hours in the day!
if we need to have one before adding it you might have to hold off for a while, most people can contact me via discord anyway ;)

**Comment by jthiller** [comment]
Hi @ccall48, going to close this PR for tidying-up purposes. Please feel free to re-add this when information and pricing is publicly available

**Comment by ccall48** [comment]
Can you re-add this joey? I noticed there are other providers who don't show pricing yet ours was yeeted for this purpose?

**Comment by jthiller** [comment]
I'm looking for there to at least be some way for someone to sign up. Even if that's a contact form.
As-is it's not particularly public.

**Pull request closed without merging**
