### PR TITLE
Update Realms to Modular Governance

### PR DESCRIPTION
**Pull request by heatedlime**
Removed reference of realms being used for voting and staking, and updated it to Helium Vote / Modular Governance.

I need to first learn how to view my changes to make sure the format looks right in HTML. Will ask this on the call tomorrow.

### CODE REVIEW

**Comment by heatedlime** [comment]
Screen Shot 2024-02-07 at 1 00 48 PM

**Comment by heatedlime** [comment]
IMG_7954
Screen Shot 2024-02-07 at 1 14 21 PM
Screen Shot 2024-02-07 at 1 13 53 PM

**Comment by heatedlime** [comment]
Helium Vote

**Comment by heatedlime** [comment]
Screen Shot 2024-02-07 at 1 13 53 PM

**Comment by heatedlime** [comment]
IMG_7956

**Comment by heatedlime** [comment]
IMG_7958

**Comment by waveform06** [comment]
realms.mdx will be deleted and replaced with either modulargovernance.mdx or heliumvote.mdx
Is this PR making that name change assumption?

**Comment by jthiller** [comment]
looking forward to this refactor! Marking this as draft while it is in-progress

**Comment by heatedlime** [comment]
@jthiller something is broken in here as well, and I can't figure it out. Whenever you have time, can you help me out?

**Comment by jthiller** [comment]
Already on it. Will have the fix up tonight for ya.

-Joey Hiller

**Comment by jthiller** [comment]
Fixed the build and rebased to all the latest changes on `master`.

**Pull request closed without merging**
