### PR TITLE
add Nebra api link

### PR DESCRIPTION
**Pull request by shawaj**

### CODE REVIEW

**Comment by samgutentag** [comment]
hey @shawaj very exciting! is this API live yet? the URL here redirects to the Nebra homepage

**Comment by shawaj** [comment]
Oh that's odd, it should be going to the API notifications sign-up page. Must have been hooked up wrong

I'll check with the team to fix this and report back

API will be live in next week or two I think.

**Comment by abhay** [comment]
exciting!

**Comment by jthiller** [comment]
Going to close this for now. Please feel free to reopen a PR alongside API availability

**Comment by shawaj** [comment]
@jthiller it's available already 🙂

**Pull request closed without merging**
