### PR TITLE
Explain: COTX X3 is Full hotspot Miner, Light hotspot and data only hotspot are other types.

### PR DESCRIPTION
**Pull request by cotxliang**

### CODE REVIEW

**Comment by cotxliang** [comment]
@madninja The customer has misinterpreted the product category of our Cotx X3, and I have already explained the problem.

**Comment by madninja** [comment]
Understood. If the light hotspots are still in development and not available then maybe this guide should not be here at all?

**Comment by cotxliang** [comment]
> Understood. If the light hotspots are still in development and not available then maybe this guide should not be here at all?

How can I modify it better, so that customers will not misinterpret it？

**Comment by madninja** [comment]
> > Understood. If the light hotspots are still in development and not available then maybe this guide should not be here at all?
> 
> How can I modify it better, so that customers will not misinterpret it？

if cotx has no light gateways for sale, remove this guide and the link in the light hotspot overview. Full hotspots are not listed anywhere near light hotspots.

**Pull request closed without merging**
