### PR TITLE
Update hotspot-makers.mdx

### PR DESCRIPTION
**Pull request by moguy1973**
Updated Pisces website to greenpalmiot.com

### CODE REVIEW

**Comment by waveform06** [comment]
https://piscesiot.com/ is the one they want people to use

**Comment by moguy1973** [comment]
> https://piscesiot.com/ is the one they want people to use

It doesn't work anymore though?

Oh wait, piscesminer.com doesn't work anymore

**Review by jthiller — APPROVED** [review]

**Comment by moguy1973** [comment]
Thanks!  Sorry about the dupe.  This was my first ever pull request. :)

**Comment by waveform06** [comment]
@moguy1973 Thats how I started,  making simple corrections and updates.

**Pull request merged**
