### PR TITLE
Externalize API key

### PR DESCRIPTION
**Pull request by 0lav**
Externalize Algolia search API credentials to not expose it.

### CODE REVIEW

**Comment by jthiller** [comment]
good catch. @mbthiery mind taking a look at this?

**Comment by mbthiery** [comment]
Algolia API keys are public by their nature (if you arent using a proxy which adds latency). If we do this we need to still keep them public/visible in this repo for contributors' sake.
Screenshot 2024-02-02 at 4 57 50 PM

**Comment by jthiller** [comment]
Thank you for submitting updates to the Helium Docs as part of the Solana Scribes Hackathon! Please follow the instructions in this form so we may begin issuing awards.

[https://forms.gle/z4ovMHYDo7pzy8TN6](https://forms.gle/z4ovMHYDo7pzy8TN6)

Please complete this form by March 15, 2024. (Approximately 1 week from today). We had SO MANY great submissions and we’re eager to distribute the awards to all of the contributors.

**Comment by 0lav** [comment]
cancel

**Comment by jthiller** [comment]
Going to keep the key included per Matthew's note and to keep dev experience clean

**Pull request closed without merging**
