### PR TITLE
Update build-a-packet-forwarder.mdx

### PR DESCRIPTION
**Pull request by BFGNeil**
changed the warning to hopefully make it clearer to hosts about earnings, and killed the discord link to stop feedback and folks finding older posts that are not relevant anymore.

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks. Can we get a link in here to the new Light Gateway roadmap page?

https://docs.helium.com/mine-hnt/light-hotspots

This is where these DIYers should be focusing their efforts moving forward.

**Comment by PharkMillups** [comment]
@BFGNeil Ping.

**Comment by BFGNeil** [comment]
updated! sorry, pretty new to git and made some mistakes!

**Review by PharkMillups — APPROVED** [review]
Thanks!

**Pull request merged**
