### PR TITLE
Complete Development Devices Port

### PR DESCRIPTION
**Pull request by kent-williams**

### CODE REVIEW

**Review by lthiery — COMMENTED** [review]
`docs/use-the-network/devices/development` is empty. maybe just put a real short definition of what we consider "Development Devices"?
image

**Comment by lthiery** [comment]
I don't understand the `::warning` header at each Arduino guide:

```
Before we begin, please make sure you've followed the steps from this guide, which goes over some initial setup steps.
```

It seems like you've labelled, "Before starting this guide please follow this guide"?

**Comment by kent-williams** [comment]
> `docs/use-the-network/devices/development` is empty. maybe just put a real short definition of what we consider "Development Devices"?
> image

It will come.. Just getting the devices in there for now

**Comment by kent-williams** [comment]
> I don't understand the `::warning` header at each Arduino guide:
> 
> ```
> Before we begin, please make sure you've followed the steps from this guide, which goes over some initial setup steps.
> ```
> 
> It seems like you've labelled, "Before starting this guide please follow this guide"?

I had to remove the link to the console quickstart for now since it doesn't exist.

**Comment by lthiery** [comment]
> > I don't understand the `::warning` header at each Arduino guide:
> > ```
> > Before we begin, please make sure you've followed the steps from this guide, which goes over some initial setup steps.
> > ```
> > 
> > 
> > It seems like you've labelled, "Before starting this guide please follow this guide"?
> 
> I had to remove the link to the console quickstart for now since it doesn't exist.

gotcha

**Review by lthiery — APPROVED** [review]

**Comment by lthiery** [comment]
> > `docs/use-the-network/devices/development` is empty. maybe just put a real short definition of what we consider "Development Devices"?
> > image
> 
> It will come.. Just getting the devices in there for now

okeidoke

**Pull request merged**
