### PR TITLE
Manually generate freq. tables from CSV

### PR DESCRIPTION
**Pull request by King-of-Spades**
applying the suggestions highlighted in review on https://github.com/helium/docs/pull/386

This is a manual CSV generation from https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv using https://www.convertcsv.com/csv-to-markdown.htm

Ideally auto-generation would be even better, but full autogen isn't trivial for me atm (this only took ~30 mins).

### CODE REVIEW

**Comment by King-of-Spades** [comment]
@lthiery update based on your feedback. Not automated but freshly synced to https://github.com/helium/miner/blob/master/priv/countries_reg_domains.csv

Assuming this approach is sufficient for the moment, this PR should supersede any outstanding updates to the Freq. tables.

**Comment by lthiery** [comment]
This is definitely what I was hoping for. How did you get the headers with alphabet letters?

**Comment by King-of-Spades** [comment]
@lthiery Copy-paste and determination. 😂 

I mean, if I really wanted to I probably could've written a CSV parsing script, and added that too, but again this was just a quick project...parsing might not be complicated but I'm juggling lots right now and am ready for the weekend 🎊

**Comment by lthiery** [comment]
I’ll take it! With hopes of scripting it later

**Review by lthiery — APPROVED** [review]

**Pull request merged**
